---
dependencies: []

galaxy_info:
  author: fubarhouse
  description: Provisions Node.js and a collection of NPM packages via NVM.
  license: "license (BSD, MIT)"
  min_ansible_version: 1.9.2
  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  categories:
    - system
    - database
    - development
