---
# file: roles/fubarhouse.npm/tasks/main.yml

- name: "Define user variable for ssh use"
  set_fact:
    fubarhouse_user: "{{ ansible_ssh_user }}"
  when: ansible_ssh_user is defined

- name: "Define user variable for non-ssh use"
  set_fact:
    fubarhouse_user: "{{ ansible_user_id }}"
  when: ansible_ssh_user is not defined

- name: "Define OS-specific variables"
  include_vars: "config-{{ ansible_os_family }}.yml"
  when: fubarhouse_npm is not defined

- include: "dependencies-{{ ansible_os_family}}.yml"

- include: nvm.yml
  when: fubarhouse_npm.install_nvm

- include: nodejs.yml
  when: fubarhouse_npm.install_nodejs

- include: iojs.yml
  when: fubarhouse_npm.install_iojs

- include: npm.yml
  when: fubarhouse_npm.install_npm
