---
# Tasks file for NodeJS

- name: "NodeJS | Check"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  shell:  "{{ fubarhouse_npm.nvm_symlink_exec }} ls"
  register: installed_nodejs_versions

- name: "NodeJS | Install default version"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  shell:  "{{ fubarhouse_npm.nvm_symlink_exec }} install {{ node_version }}"
  when: '"{{ node_version }}" not in "{{ node_versions }}" and "{{ node_version }}" not in "{{ installed_nodejs_versions.stdout }}"'

- name: "NodeJS | Install all requested versions"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  shell:  "{{ fubarhouse_npm.nvm_symlink_exec }} install {{ item }}"
  when: item not in installed_nodejs_versions.stdout
  with_items: "{{ node_versions }}"

- name: "NodeJS | Switching"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  shell:  "{{ fubarhouse_npm.nvm_symlink_exec }} use {{ node_version }}"
  register: fubarhouse_npm_switch
  changed_when: fubarhouse_npm_switch.stdout.find('Now using node v{{ node_version }}') != -1

- name: "NodeJS | Linking"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  shell:  "{{ fubarhouse_npm.nvm_symlink_exec }} alias default {{ node_version }}"

- name: "NodeJS | Import exports"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  lineinfile:
    dest: "{{ fubarhouse_npm.user_dir }}/{{ item.filename }}"
    line: "export PATH=$PATH:$(npm config --global get prefix)/bin"
    state: present
  with_items: "{{ fubarhouse_npm.shell_profiles }}"
