---
# Tasks file for NPM

- name: "NPM | Make sure NPM can be found"
  shell: which npm | cat
  failed_when: false
  changed_when: false
  register: which_npm

- name: "NPM | Ensure installed and updated"
  become_user: "{{ fubarhouse_user }}"
  npm:
    name: "{{ item }}"
    executable: "{{ which_npm.stdout }}"
    global: yes
  with_items:
    - "{{ node_packages }}"
  when: '"npm" in which_npm.stdout'
