---
# Tasks file for NPM

- name: "NPM | Configure"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  shell: "{{ fubarhouse_npm.npm_install_exec }} config set prefix /usr/local"

- name: "NPM | Ensure installed and updated"
  become: yes
  become_user: root
  npm:
    name: "{{ item }}"
    executable: "{{ fubarhouse_npm.npm_install_exec }}"
    global: yes
  with_items:
    - "{{ node_packages }}"
